build(#1): rnp-components: nx failing due to misplaced test-setup.ts
```
Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it. See errors below.

Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
      An error occurred while processing files for the @nx/jest/plugin plugin.
    - libs/rnp-components/jest.config.ts: ● Validation Error:

    Module <rootDir>/src/test-setup.ts in the setupFilesAfterEnv option was not found.
           <rootDir> is: /home/USER/programming/teatime/libs/rnp-components

    Configuration Documentation:
    https://jestjs.io/docs/configuration

      Error: ● Validation Error:

        Module <rootDir>/src/test-setup.ts in the setupFilesAfterEnv option was not found.
               <rootDir> is: /home/USER/programming/teatime/libs/rnp-components

        Configuration Documentation:
        https://jestjs.io/docs/configuration
```